#!/bin/sh
set -e
chmod +x /opt/lightning-l2/setup.sh /opt/lightning-l2/launch.sh
update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
gtk-update-icon-cache /usr/share/icons/hicolor >/dev/null 2>&1 || true
exit 0
